### ISSUE TITLE
Music cutting out

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/AldoBot.js#1]
Bot crashes near the end of a song
Log
2020-04-19T20:05:09.200827+00:00 app[worker.1]: events.js:288
2020-04-19T20:05:09.200837+00:00 app[worker.1]:       throw er; // Unhandled 'error' event
2020-04-19T20:05:09.200838+00:00 app[worker.1]:       ^
2020-04-19T20:05:09.200838+00:00 app[worker.1]: 
2020-04-19T20:05:09.200839+00:00 app[worker.1]: Error: Status code: 416
2020-04-19T20:05:09.200840+00:00 app[worker.1]:     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:128:27)
2020-04-19T20:05:09.200840+00:00 app[worker.1]:     at Object.onceWrapper (events.js:418:26)
2020-04-19T20:05:09.200841+00:00 app[worker.1]:     at ClientRequest.emit (events.js:311:20)
2020-04-19T20:05:09.200841+00:00 app[worker.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
2020-04-19T20:05:09.200841+00:00 app[worker.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
2020-04-19T20:05:09.200842+00:00 app[worker.1]:     at TLSSocket.socketOnData (_http_client.js:476:22)
2020-04-19T20:05:09.200842+00:00 app[worker.1]:     at TLSSocket.emit (events.js:311:20)
2020-04-19T20:05:09.200842+00:00 app[worker.1]:     at addChunk (_stream_readable.js:294:12)
2020-04-19T20:05:09.200843+00:00 app[worker.1]:     at readableAddChunk (_stream_readable.js:275:11)
2020-04-19T20:05:09.200843+00:00 app[worker.1]:     at TLSSocket.Readable.push (_stream_readable.js:209:10)
2020-04-19T20:05:09.200843+00:00 app[worker.1]: Emitted 'error' event on PassThrough instance at:
2020-04-19T20:05:09.200844+00:00 app[worker.1]:     at PassThrough.<anonymous> (/app/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/index.js:133:14)
2020-04-19T20:05:09.200844+00:00 app[worker.1]:     at PassThrough.emit (events.js:311:20)
2020-04-19T20:05:09.200844+00:00 app[worker.1]:     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:133:28)
2020-04-19T20:05:09.200845+00:00 app[worker.1]:     at Object.onceWrapper (events.js:418:26)
2020-04-19T20:05:09.200845+00:00 app[worker.1]:     [... lines matching original stack trace ...]
2020-04-19T20:05:09.200845+00:00 app[worker.1]:     at addChunk (_stream_readable.js:294:12)

**Comment by AldoAbdn** [comment]
Fixed, needed to update dependencies and change 'end' event to 'finish'

**Comment by AldoAbdn** [comment]
Fixed, issue with URL
